apiVersion: apps/v1
kind: Deployment
metadata:
  name: command-execution
  namespace: default
spec:
  selector:
    matchLabels:
      app: external-kubectl
  template:
    metadata:
      name: command-execution
      labels:
        app: external-kubectl
    spec:
      serviceAccountName: internal-kubectl
      containers:
      - name: tester
        image: bitnami/kubectl:1.22.3
        env:
          - name: JobOutputFolder
            value: "/home"
        volumeMounts:
          - mountPath: "/home"
            name: volume
        command:
         - "bin/bash"
         - "-c"
         - |
           echo "running below scripts"
           c=1
           while [ $c -le 500 ]
           do
          
           res=$(curl -s -o /dev/null -w "%{http_code}" http://mints-gateway-api-service:8000/checkJwtUpdate)
           response=$(curl -sb -H "Accept: application/json" "http://mints-gateway-api-service:8000/checkJwtUpdate") 

           if [[ $res -eq 200 ]]; then

           kubectl get pods
           echo "updated"

           else
  
           echo "not updated"

           fi
           
           sleep 10

           (( c++ ))

           done
           sleep 300           
      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: data-camelapp
      restartPolicy: Always
