---
kind: Service
apiVersion: v1
metadata:
  name: mints-ui-service
  namespace: default
spec:
  selector:
    app: mints-ui-service
  ports:
    - protocol: TCP
      #Port accessible inside cluster
      port: 3000
      # Port to forward to inside the pod
      targetPort: 3000
    - protocol: TCP
      #Port accessible inside cluster
      port: 7000
      # Port to forward to inside the pod
      targetPort: 7000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mints-ui-service
  namespace: default
spec:
  selector:
    matchLabels:
      app: mints-ui-service
  replicas: 1
  minReadySeconds: 15
  template:
    metadata:
      labels:
        app: mints-ui-service
    spec:
      containers:
        - name: mints-ui-service
          image: msslabsbentonville/mintui:324
          imagePullPolicy: Always
          #resources:
          #requests:
          #memory: "400Mi"
          #cpu: "500m"
          ports:
            - containerPort: 3000
              protocol: TCP
            - containerPort: 7000
              protocol: TCP
