---
kind: Service
apiVersion: v1
metadata:
  name: user-clocks-service
  namespace: default
spec:
  selector:
    app: user-clocks-service
  ports:
    - protocol: TCP
      #Port accessible inside cluster
      port: 7000
      # Port to forward to inside the pod
      targetPort: 7000
      #Port accessible outside cluster
      #reactappPort: 30567
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-clocks-service
  namespace: default
spec:
  selector:
    matchLabels:
      app: user-clocks-service
  replicas: 1
  minReadySeconds: 15
  template:
    metadata:
      labels:
        app: user-clocks-service
    spec:
      containers:
        - name: user-clocks-service
          image: msslabsbentonville/user-clocks:1168
          imagePullPolicy: Always
          #resources:
          #requests:
          #memory: "400Mi"
          #cpu: "500m"
          ports:
            - containerPort: 7000
              protocol: TCP
