apiVersion: v1
kind: Service
metadata:
  name: jmapperframework
  namespace: default
spec:
  selector:
    app: jmapperframework
  ports:
    - protocol: TCP
      #Port accessible inside cluster
      port: 8080
      # Port to forward to inside the pod
      targetPort: 8080
      #Port accessible outside cluster
      #reactappPort: 30567
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jmapperframework
  namespace: default
spec:
  selector:
    matchLabels:
      app: jmapperframework
  replicas: 1
  minReadySeconds: 15
  template:
    metadata:
      labels:
        app: jmapperframework
    spec:
      containers:
        - name: jmapperframework
          image: msslabsbentonville/jmapperframework:587
          imagePullPolicy: Always

          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: routes
              mountPath: /usr/mints/global_eai
            - name: routes
              mountPath: /usr/src/app/resources
      volumes:
        - name: routes
          persistentVolumeClaim:
            claimName: data-camelapp
